version: "3.7"

services:
  caddy:
    image: caddy:2.6.4
    restart: unless-stopped
    network_mode: host
    volumes:
      - $CADDY_DIR:/etc/caddy:ro
      - $CADDY_DATA:/data
      - $CADDY_CONFIG:/config
