version: '3'

services:
  drone:
    image: drone/drone:2.18.0
    networks:
      app:
        ipv4_address: 10.10.8.1
      db: null
    environment:
      DRONE_GITHUB_CLIENT_ID: $DRONE_GITHUB_CLIENT_ID
      DRONE_GITHUB_CLIENT_SECRET: $DRONE_GITHUB_CLIENT_SECRET
      DRONE_RPC_SECRET: $DRONE_RPC_SECRET
      DRONE_SERVER_HOST: $DRONE_SERVER_HOST
      DRONE_SERVER_PROTO: https
      DRONE_DATABASE_DRIVER: postgres
      DRONE_DATABASE_DATASOURCE: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db/$POSTGRES_DB?sslmode=disable
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12-alpine
    networks:
      db: null
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - $POSTGRES_DATA_DIR:/var/lib/postgresql/data
    restart: always
  
  db-backup:
    image: ghcr.io/tiredofit/docker-db-backup:3.9.1
    networks:
      db: null
    depends_on:
      - db
    volumes:
      - $DRONE_DB_BACKUP:/backup
    environment:
      - DB_TYPE=pgsql
      - DB_HOST=db
      - DB_NAME=$POSTGRES_DB
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
      - DB_DUMP_FREQ=10080        # backup once a week
      - DB_DUMP_BEGIN=0235        # backup at 2:35am
      - DB_CLEANUP_TIME=100800    # keep 10 weeks of backups
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=FALSE
      - CONTAINER_ENABLE_MONITORING=FALSE
    restart: always

networks:
  app:
    external: true
  db:
    driver: bridge
    internal: true
