version: "3.4"

services:
  app:
    image: influxdb:2.7.9
    networks:
      app:
        ipv4_address: 10.10.1.1
    volumes:
      - $INFLUXDB_DIR:/var/lib/influxdb2
    restart: always
  
  db-backup:
    image: ghcr.io/tiredofit/docker-db-backup:latest
    networks:
      app: null
    depends_on:
      - app
    volumes:
      - $INFLUXDB_DB_BACKUP:/backup
    environment:
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TZ=America/Los_Angeles
      - DEFAULT_CHECKSUM=SHA1
      - DEFAULT_COMPRESSION=GZ
      - DEFAULT_BACKUP_INTERVAL=10080 # backup once a week
      - DEFAULT_BACKUP_BEGIN=0415     # backup at 4:15am
      - DEFAULT_CLEANUP_TIME=100800   # keep 10 weeks of backups

      - DB01_TYPE=influx
      - DB01_HOST=http://app
      - DB01_NAME=ALL
      - DB01_USER=$INFLUXDB_ORG
      - DB01_PASS=$INFLUXDB_TOKEN
      - DB01_INFLUX_VERSION=2
    restart: always

networks:
  app:
    external: true
