version: "3.4"

services:
  app:
    image: monica:4.0.0-apache
    depends_on:
      - db
    environment:
      - APP_KEY=$APP_KEY
      - APP_URL=$APP_URL
      - APP_DISABLE_SIGNUP=true
      - APP_TRUSTED_PROXIES=$APP_TRUSTED_PROXIES
      - APP_ENV=production
      - HASH_SALT=$HASH_SALT
      - HASH_LENGTH=18
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=$MYSQL_PASSWORD
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=$MAIL_USERNAME
      - MAIL_PASSWORD=$MAIL_PASSWORD
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS
      - MAIL_FROM_NAME="monica"
    networks:
      - db
      - app
    volumes:
      - $MONICA_STORAGE:/var/www/html/storage
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 2m
      timeout: 3s
    restart: always

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    networks:
      - db
    volumes:
      - $MYSQL_DATA:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2m
      timeout: 3s
    restart: always

  cron:
    image: monica:4.0.0-apache
    command: cron.sh
    depends_on:
      - db
    environment:
      - APP_KEY=$APP_KEY
      - APP_URL=$APP_URL
      - APP_DISABLE_SIGNUP=true
      - APP_TRUSTED_PROXIES=$APP_TRUSTED_PROXIES
      - APP_ENV=production
      - HASH_SALT=$HASH_SALT
      - HASH_LENGTH=18
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=$MYSQL_PASSWORD
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=$MAIL_USERNAME
      - MAIL_PASSWORD=$MAIL_PASSWORD
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS
      - MAIL_FROM_NAME="monica"
    networks:
      - db
      - app
    volumes:
      - $MONICA_STORAGE:/var/www/html/storage
    restart: always
  
  db-backup:
    image: tiredofit/db-backup
    networks:
      - db
    depends_on:
      - db
    volumes:
      - $MONICA_DB_BACKUP:/backup
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_NAME=monica
      - DB_USER=monica
      - DB_PASS=$MYSQL_PASSWORD
      - DB_DUMP_FREQ=10080        # backup once a week
      - DB_DUMP_BEGIN=0215        # backup at 2:15am
      - DB_CLEANUP_TIME=FALSE     # don't cleanup old backups
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=FALSE
      - CONTAINER_ENABLE_MONITORING=FALSE
    restart: always

networks:
  db:
    driver: bridge
    internal: true
  app:
    driver: bridge
