services:
  broker:
    image: docker.io/library/redis:7-alpine
    networks:
      db: null
    volumes:
      - $PAPERLESS_DIR/redisdata:/data
    restart: always
  
  postgres:
    image: docker.io/library/postgres:17-alpine
    networks:
      db: null
    restart: unless-stopped
    volumes:
      - $PAPERLESS_DIR/pgdata:/var/lib/postgresql/data
    environment:
      TZ: America/Los_Angeles
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.14.7
    networks:
      app:
        ipv4_address: 10.10.10.1
      db: null
    depends_on:
      - broker
      - postgres
    volumes:
      - $PAPERLESS_DIR/data:/usr/src/paperless/data
      - $PAPERLESS_DIR/media:/usr/src/paperless/media
      - $PAPERLESS_DIR/export:/usr/src/paperless/export
      - $PAPERLESS_DIR/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DATE_ORDER: MDY
      PAPERLESS_TIME_ZONE: America/Los_Angeles
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
      PAPERLESS_SECRET_KEY: $PAPERLESS_SECRET_KEY
      PAPERLESS_URL: $PAPERLESS_URL
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBPASS: $POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 60s
      timeout: 10s
      retries: 5
    restart: always

  db-backup:
    image: ghcr.io/tiredofit/docker-db-backup:latest
    networks:
      db: null
    depends_on:
      - postgres
    volumes:
      - $PAPERLESS_DB_BACKUP:/backup
      - $PAPERLESS_DIR/data:/data:ro
    environment:
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TZ=America/Los_Angeles
      - DEFAULT_CHECKSUM=SHA1
      - DEFAULT_COMPRESSION=GZ
      - DEFAULT_BACKUP_INTERVAL=10080 # backup once a week
      - DEFAULT_BACKUP_BEGIN=0230     # backup at 2:30am
      - DEFAULT_CLEANUP_TIME=100800   # keep 10 weeks of backups
  
      - DB01_TYPE=pgsql
      - DB01_HOST=postgres
      - DB01_NAME=ALL
      - DB01_USER=paperless
      - DB01_PASS=$POSTGRES_PASSWORD
    restart: always

networks:
  app:
    external: true
  db:
    driver: bridge
    internal: true