version: "3"

services:
  db:
    image: mariadb:10.5
    networks:
      - db
    environment:
      - MARIADB_DATABASE=photoview
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - $PHOTOVIEW_DATA:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 3s
    restart: always

  photoview:
    image: viktorstrate/photoview:2.3.13
    networks:
      - db
      - server
    ports:
      - "$PHOTOVIEW_PORT:4001"
    depends_on:
      - db
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=$MARIADB_USER:$MARIADB_PASSWORD@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      
      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1
      
      
      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      - $PHOTOVIEW_API_CACHE:/app/cache
      - $PHOTOVIEW_PHOTO_PATH:/photos:ro
    restart: always

networks:
  db:
    driver: bridge
    internal: true
  server:
    driver: bridge
