services:
  shiori:
    image: ghcr.io/go-shiori/shiori:v1.7.4
    networks:
      app:
        ipv4_address: 10.10.9.1
    volumes:
      - $SHIORI_DIR:/shiori
      - $SHIORI_ARCHIVE_DIR:/shiori/archive
    restart: always
  
  db-backup:
    image: ghcr.io/tiredofit/docker-db-backup:latest
    depends_on:
      - shiori
    volumes:
      - $SHIORI_DB_BACKUP:/backup
      - $SHIORI_DIR:/data:ro
    environment:
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TZ=America/Los_Angeles
      - DEFAULT_CHECKSUM=SHA1
      - DEFAULT_COMPRESSION=GZ
      - DEFAULT_BACKUP_INTERVAL=10080 # backup once a week
      - DEFAULT_BACKUP_BEGIN=0220     # backup at 2:20am
      - DEFAULT_CLEANUP_TIME=50400    # keep 5 weeks of backups

      - DB01_TYPE=sqlite3
      - DB01_HOST=/data/shiori.db
      - DB01_NAME=ALL
    restart: always

networks:
  app:
    external: true