---
services:
  umami:
    image: docker.umami.dev/umami-software/umami:postgresql-v2.16.1
    networks:
      app:
        ipv4_address: 10.10.4.1
      db: null
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: $HASH_SALT
    depends_on:
      - db
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 30s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    networks:
      db: null
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: $POSTGRES_ROOT_USER
      POSTGRES_PASSWORD: $POSTGRES_ROOT_PASSWORD
    volumes:
      - $POSTGRES_DATA_DIR:/var/lib/postgresql/data
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5

  db-backup:
    image: ghcr.io/tiredofit/docker-db-backup:latest
    networks:
      db: null
    depends_on:
      - db
    volumes:
      - $UMAMI_DB_BACKUP:/backup
    environment:
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TZ=America/Los_Angeles
      - DEFAULT_CHECKSUM=SHA1
      - DEFAULT_COMPRESSION=GZ
      - DEFAULT_BACKUP_INTERVAL=1440  # backup once a day
      - DEFAULT_BACKUP_BEGIN=0230     # backup at 2:30am
      - DEFAULT_CLEANUP_TIME=43200    # clean up backups older than 30 days

      - DB01_TYPE=pgsql
      - DB01_HOST=db
      - DB01_NAME=umami
      - DB01_USER=$POSTGRES_USER
      - DB01_PASS=$POSTGRES_PASSWORD
    restart: 'unless-stopped'

networks:
  app:
    external: true
  db:
    driver: bridge
    internal: true
