---
version: '3'
services:
  umami:
    image: docker.umami.dev/umami-software/umami:postgresql-v2.6.2
    networks:
      app:
        ipv4_address: 10.10.4.1
      db: null
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: $HASH_SALT
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    networks:
      db: null
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: $POSTGRES_ROOT_USER
      POSTGRES_PASSWORD: $POSTGRES_ROOT_PASSWORD
    volumes:
      - $POSTGRES_DATA_DIR:/var/lib/postgresql/data
    restart: always

  db-backup:
    image: ghcr.io/tiredofit/docker-db-backup:3.9.9
    networks:
      db: null
    depends_on:
      - db
    volumes:
      - $UMAMI_DB_BACKUP:/backup
    environment:
      - DB_TYPE=pgsql
      - DB_HOST=db
      - DB_NAME=umami
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
      - DB_DUMP_FREQ=1440         # backup once a day
      - DB_DUMP_BEGIN=0230        # backup at 2:30am
      - DB_CLEANUP_TIME=43200     # clean up backups older than 30 days
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=FALSE
      - CONTAINER_ENABLE_MONITORING=FALSE
    restart: always

networks:
  app:
    external: true
  db:
    driver: bridge
    internal: true
