version: '3'

services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.32.3-alpine
    restart: always
    volumes:
      - $VAULTWARDEN_DATA:/data
    networks:
      app:
        ipv4_address: 10.10.5.1
    environment:
      - DOMAIN=$VAULTWARDEN_DOMAIN
      - ADMIN_TOKEN=$ADMIN_TOKEN
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - SMTP_FROM=$SMTP_FROM
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=$SMTP_USER
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - TZ=America/Los_Angeles
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/alive"]
      interval: 1m
      timeout: 3s
      start_period: 10s

  db-backup:
    image: ghcr.io/tiredofit/docker-db-backup:latest
    depends_on:
      - vaultwarden
    volumes:
      - $VAULTWARDEN_DB_BACKUP:/backup
      - $VAULTWARDEN_DATA:/data:ro
    environment:
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TZ=America/Los_Angeles
      - DEFAULT_CHECKSUM=SHA1
      - DEFAULT_COMPRESSION=GZ
      - DEFAULT_BACKUP_INTERVAL=1440 # backup once a day
      - DEFAULT_BACKUP_BEGIN=0130    # backup at 1:30am
      - DEFAULT_CLEANUP_TIME=43200   # keep 30 days of old backups

      - DB01_TYPE=sqlite3
      - DB01_HOST=/data/db.sqlite3
      - DB01_NAME=ALL
    restart: always

networks:
  app:
    external: true
